baseURL = 'https://dianaventura.github.io/'
languageCode = 'en-gb'
title = 'the-Penniless-Scholar'
copyright = "Copyright © 2024, Diana Ventura Valdivia."

[params]
  author = "Diana Ventura Valdivia"
  description = "A simple, calm blog"
  showDarkMode = true

# Generate a nice robots.txt for SEO
enableRobotsTXT = true